- hosts: tomcatServer
  sudo: yes
  vars:
  - warName: sample.war
  - warRemotePath: /opt/tomcat

  tasks:
  - name: Download WAR to server
    synchronize: src={{ warName }} dest={{ warRemotePath }}/{{ warName }}
    notify:
        - Restart tomcat8

  - name: Delete remote war file
    file: path={{ warRemotePath }}/{{ warName }} state=absent

  handlers:
    - name: Restart tomcat8
      service: name=tomcat8 state=restarted
